# Screen dimensions
WIDTH = 800
HEIGHT = 800

# Road dimensions
ROAD_WIDTH = 100
LANE_WIDTH = ROAD_WIDTH // 2

# Traffic light dimensions
LIGHT_SIZE = 15
LIGHT_SPACING = 5
LIGHT_BOX_HEIGHT = 3 * LIGHT_SIZE + 4 * LIGHT_SPACING
LIGHT_BOX_WIDTH = LIGHT_SIZE + 2 * LIGHT_SPACING

# Traffic light coordinates
LIGHT_LEFT_X = WIDTH//2 - ROAD_WIDTH//2 - LIGHT_BOX_WIDTH - 10
LIGHT_LEFT_Y = HEIGHT//2 - LIGHT_BOX_HEIGHT//2
LIGHT_TOP_X = WIDTH//2 - LIGHT_BOX_WIDTH//2
LIGHT_TOP_Y = HEIGHT//2 - ROAD_WIDTH//2 - LIGHT_BOX_HEIGHT - 10
LIGHT_RIGHT_X = WIDTH//2 + ROAD_WIDTH//2 + 10
LIGHT_RIGHT_Y = HEIGHT//2 - LIGHT_BOX_HEIGHT//2
LIGHT_BOTTOM_X = WIDTH//2 - LIGHT_BOX_WIDTH//2
LIGHT_BOTTOM_Y = HEIGHT//2 + ROAD_WIDTH//2 + 10

# Default car properties
START_POS = [[-WIDTH//2, 0], [0, HEIGHT//2], [WIDTH//2, 0], [0, -HEIGHT//2]]
DIRECTIONS = [0, 1, 2, 3]
CAR_SPEED = 2
CAR_RADIUS = 10
CAR_SPAWN_RATE = 0.1

FPS = 120

# Colors
WHITE = (255, 255, 255)
GRAY = (100, 100, 100)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)